"""add_content_columns

Revision ID: 375d1ef35454
Revises: 6e8e48a17a0f
Create Date: 2026-04-14 11:15:23.910807

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '375d1ef35454'
down_revision: Union[str, Sequence[str], None] = '6e8e48a17a0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('key_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('articles', sa.Column('image_url', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('author', sa.String(length=255), nullable=True))
    op.add_column('articles', sa.Column('content_scraped', sa.Boolean(), server_default='false', nullable=False))
    op.create_index('ix_article_content_scraped', 'articles', ['content_scraped'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_article_content_scraped', table_name='articles')
    op.drop_column('articles', 'content_scraped')
    op.drop_column('articles', 'author')
    op.drop_column('articles', 'image_url')
    op.drop_column('articles', 'key_points')
    op.drop_column('articles', 'content')
    # ### end Alembic commands ###
