"""add insider_trades earnings_events social_sentiments tables

Revision ID: 6304dc0a2143
Revises: 375d1ef35454
Create Date: 2026-04-18 15:47:40.428940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6304dc0a2143'
down_revision: Union[str, Sequence[str], None] = '375d1ef35454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('earnings_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('report_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estimated_eps', sa.Float(), nullable=True),
    sa.Column('actual_eps', sa.Float(), nullable=True),
    sa.Column('estimated_revenue', sa.Float(), nullable=True),
    sa.Column('actual_revenue', sa.Float(), nullable=True),
    sa.Column('surprise_pct', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_earnings_source_id')
    )
    op.create_index(op.f('ix_earnings_events_ticker'), 'earnings_events', ['ticker'], unique=False)
    op.create_index('ix_earnings_report_date', 'earnings_events', ['report_date'], unique=False)
    op.create_table('insider_trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('officer_name', sa.String(length=255), nullable=False),
    sa.Column('officer_title', sa.String(length=255), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('filing_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_insider_trade_source_id')
    )
    op.create_index('ix_insider_trade_filing_date', 'insider_trades', ['filing_date'], unique=False)
    op.create_index('ix_insider_trade_type', 'insider_trades', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_insider_trades_ticker'), 'insider_trades', ['ticker'], unique=False)
    op.create_table('social_sentiments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('post_title', sa.Text(), nullable=False),
    sa.Column('post_body', sa.Text(), nullable=True),
    sa.Column('post_score', sa.Integer(), nullable=False),
    sa.Column('subreddit', sa.String(length=50), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('sentiment_label', sa.String(length=20), nullable=False),
    sa.Column('tickers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'source_id', name='uq_social_platform_source_id')
    )
    op.create_index('ix_social_platform', 'social_sentiments', ['platform'], unique=False)
    op.create_index('ix_social_posted_at', 'social_sentiments', ['posted_at'], unique=False)
    op.create_index('ix_social_sentiment', 'social_sentiments', ['sentiment_score'], unique=False)
    op.create_index(op.f('ix_social_sentiments_ticker'), 'social_sentiments', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_sentiments_ticker'), table_name='social_sentiments')
    op.drop_index('ix_social_sentiment', table_name='social_sentiments')
    op.drop_index('ix_social_posted_at', table_name='social_sentiments')
    op.drop_index('ix_social_platform', table_name='social_sentiments')
    op.drop_table('social_sentiments')
    op.drop_index(op.f('ix_insider_trades_ticker'), table_name='insider_trades')
    op.drop_index('ix_insider_trade_type', table_name='insider_trades')
    op.drop_index('ix_insider_trade_filing_date', table_name='insider_trades')
    op.drop_table('insider_trades')
    op.drop_index('ix_earnings_report_date', table_name='earnings_events')
    op.drop_index(op.f('ix_earnings_events_ticker'), table_name='earnings_events')
    op.drop_table('earnings_events')
    # ### end Alembic commands ###
