"""initial schema - articles tickers sources

Revision ID: 6e8e48a17a0f
Revises: 
Create Date: 2026-04-12 08:55:44.876095

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e8e48a17a0f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tickers', postgresql.ARRAY(sa.String(length=10)), nullable=False),
    sa.Column('sentiment', sa.Float(), nullable=True),
    sa.Column('sentiment_label', sa.String(length=20), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('raw_article_id', sa.String(length=255), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_article_source_id')
    )
    op.create_index('ix_article_published_at', 'articles', ['published_at'], unique=False)
    op.create_index('ix_article_sentiment', 'articles', ['sentiment'], unique=False)
    op.create_index('ix_article_source', 'articles', ['source'], unique=False)
    op.create_index('ix_article_tickers', 'articles', ['tickers'], unique=False, postgresql_using='gin')
    op.create_table('sources',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('tickers',
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickers')
    op.drop_table('sources')
    op.drop_index('ix_article_tickers', table_name='articles', postgresql_using='gin')
    op.drop_index('ix_article_source', table_name='articles')
    op.drop_index('ix_article_sentiment', table_name='articles')
    op.drop_index('ix_article_published_at', table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
