"""add short_interests table

Revision ID: f5c09406b3f5
Revises: 6304dc0a2143
Create Date: 2026-04-18 16:16:55.366717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5c09406b3f5'
down_revision: Union[str, Sequence[str], None] = '6304dc0a2143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_interests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('short_pct_float', sa.Float(), nullable=False),
    sa.Column('days_to_cover', sa.Float(), nullable=False),
    sa.Column('borrow_fee_pct', sa.Float(), nullable=True),
    sa.Column('squeeze_score', sa.Integer(), nullable=True),
    sa.Column('report_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_short_interest_source_id')
    )
    op.create_index('ix_short_interest_report_date', 'short_interests', ['report_date'], unique=False)
    op.create_index('ix_short_interest_squeeze', 'short_interests', ['squeeze_score'], unique=False)
    op.create_index(op.f('ix_short_interests_ticker'), 'short_interests', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_short_interests_ticker'), table_name='short_interests')
    op.drop_index('ix_short_interest_squeeze', table_name='short_interests')
    op.drop_index('ix_short_interest_report_date', table_name='short_interests')
    op.drop_table('short_interests')
    # ### end Alembic commands ###
